### ISSUE TITLE
Sparse tensor concatenation

### ISSUE THREAD

**Issue by ouenal** [traveller59/spconv#159]
Is there a way to concatenate two sparse tensors during a forward pass while retaining the gradients?

**Comment by traveller59** [comment]
if your sparse tensors have same spatial structure, just concat their features.
otherwise 
1. only regular sparse convolution support duplicate indice. duplicate indices are removed by unique. submanifold convolution don't support remove duplicate indice.
2. the gradient of duplicated tensor in regular sparse conv is: for same location between two tensors, the gradient is one of the two tensors (by torch.unique). sum/mean of duplicate indice gradient isn't supported and is hard to implement.
3. I think do convolution with concatenated tensors is undefined. you should remove duplicate indices first (duplicate element can use max). If a ```RemoveDuplicate``` layer can meet your demand, I can implement it.

**Comment by xmyqsh** [comment]
@traveller59 
1,2,3 is non-efficient. Instead of generating and removing, let's do not generate it directly.
How to achieve this? Add a new parameter to sparse conv, `outIndices`, and make the relationship between `inIndices` and `outIndices` by kernel offset. Guess what? we skip the time consuming output position generation step!

**Comment by xmyqsh** [comment]
Making the relationship between `inIndices` and `outIndices` will have time complicity of O(InAct * OutAct).
The original time complicity is O(InAct * maxKernelVolume).
So, add a line of `OutActPos.count(index - spatialVolume * indicesIn(ix, 0))` will be a better choice, with outputSpatial Volume extra space.

@traveller59 Can you come up with a better solution?

**Comment by xmyqsh** [comment]
@traveller59 
I've implemented my solution, but it only works on the inevitable operation which is the same as the invertConv does. With different downsampling and upsampling setting, some indices are unrecoverable.

By the way, I need the `RemoveDuplicate` in another work. It will be a popular op in sparse tensor. I can help to implement it.

**Comment by traveller59** [comment]
@xmyqsh actually i can't understand your solution... the problem is which layer followed by sparse concat. subm conv can't handle duplicate indices, regular conv randomly choice a indice from duplicate indices.
there is a simple python implementation of [RemoveDuplicate](https://github.com/traveller59/spconv/blob/develop/spconv/spatial.py#L27) in develop branch.

**Comment by xmyqsh** [comment]
My solution is a similar feature in `Minkowski`.
randomly choice in [RemoveDuplicate](https://github.com/traveller59/spconv/blob/develop/spconv/spatial.py#L27) is meaningless, `concat`/`mean`/`max` of duplicate features is meaningful.
