### ISSUE TITLE
nvcc fatal : Unknown option '-openmp' while running python setup.py bdist_wheel

### ISSUE THREAD

**Issue by andrewcking** [traveller59/spconv#161]
Getting same error as #139 

Is this indicative of any problem in particular?

Windows 10
CUDA 10.2
I've tried multiple pytorch versions from 1.3 to 1.5
I've tried multiple python version from 3.6.10 to 3.7.7

**Comment by traveller59** [comment]
windows 10...
you can check [dockerfile](https://github.com/traveller59/spconv/blob/master/Dockerfile). I need to install vs studio and configure windows environment first. please wait for one day.

**Comment by andrewcking** [comment]
Thanks for the reply. Yes unfortunately I need to be able to run on both Windows and Linux. Everything has been building for me on Unbuntu but I'm getting the above error when building on Windows and can't seem to spot the problem.

**Comment by traveller59** [comment]
1. openmp problem is same as ubuntu install note in README. please fix it by your self.
2. then you will encounter several MSVC constexpr bug. The first one need to modify torch include source, you can find it by google. I have no idea to solve remain bugs, best way is using clang instead of MSVC. I don't have time to working on clang compilation.

**Comment by andrewcking** [comment]
As you said I was able to clear the error by removing the flag in 'Caffe2Targets.cmake' on the PyTorch side but did run into errors after that. After quite a bit of work I gave up on a windows build, it seems some people have been successful but perhaps that was on older versions of spconv. I've scrapped Windows for now.
