### ISSUE TITLE
Cannot find rbbox_intersection, rbbox_iou

### ISSUE THREAD

**Issue by mxhong9** [traveller59/spconv#357]
I want to test the performance of spconv 2.x on a code previously using spconv 1.0; after successfully installing spconv, I encountered an error saying that it cannot import while running "from spconv.utils import rbbox_intersection, rbbox_iou".

I tried to change to "from spconv.pytorch.utils import xxx" as said in the "Breaking changes" part of the GitHub, but the error message becomes "No module named 'spconv.pytorch.utils'".

May I ask where can I find these two functions in spconv 2.x? Are they removed in the new version? Or it is just a change of name? Thanks a lot!

**Comment by FindDefinition** [comment]
They are removed because they depend on boost c++ library. currently spconv only depend on CUDA library and my other projects, no third-party software needed. I wish this project focus on heavy-optimized sparse convolution and sparse ops.
I recommend to use other implementations such as [mmcv](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/box_iou_rotated.py)
I will add ops you mentioned in spconv 2.1.0, but I still may remove them in future release.

**Comment by curiousboy20** [comment]
> They are removed because they depend on boost c++ library. currently spconv only depend on CUDA library and my other projects, no third-party software needed. I wish this project focus on heavy-optimized sparse convolution and sparse ops. I recommend to use other implementations such as [mmcv](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/box_iou_rotated.py) I will add ops you mentioned in spconv 2.1.0, but I still may remove them in future release.

Hi, I used spconv version 1.0 and got the same result. Can you tell me which version of spconv has rbbox_intersection?

**Comment by FindDefinition** [comment]
@curiousboy20 [here](https://github.com/traveller59/spconv/tree/v1.2.1)

**Comment by mxhong9** [comment]
Got it. Thanks!
