### ISSUE TITLE
inquiry， about dense to sparse?

### ISSUE THREAD

**Issue by mengshiyu0109** [traveller59/spconv#375]
Dear author,

I follow the API.md to get the method about get a sparse tensor,
so  now I met a problem.
 First , according the features and coordinates, I got a sparse tensor. And I use ". dense()" to become a  normal tensor again, and  I made some Conv operation. how can I change the normal tenor to a sparse one again? 
Is there any function?

thanks a lot

**Comment by FindDefinition** [comment]
We need to know the spatial structure of your dense tensor. after dense convs, the spatial structure is unknown.
method 1: use ```SparseConvTensor.from_dense(your_NHWC_tensor)```, input tensor must be NHWC format. this method is slow because torch need to calculate if a location is empty.
method 2: don't use dense convs, use ```SparseConv3d```.
method 3: (not available for now) run indice generation for every dense conv layer, and use that indices to gather features from dense tensor.
