### ISSUE TITLE
removing the python wrapper of the implicit_gemm 

### ISSUE THREAD

**Issue by gillbam** [traveller59/spconv#401]
Hello Yan,

Thanks for the novel idea of the GEMM. I'm trying to remove your python wrapper and implement the implicit_gemm part in C++ only style for experimenting purposes. As CUMM shows, the whole codebase provides a large wide optimization for multiple hardware architectures. However, I would like only to implement the **TIGHTEST** codebase for Ampere GPU with C++. Thus, I look forward to having some advice for the following questions:

1. If I got correct comprehension of your code, the python code selects the best parameters of the current running environment before the real C++ GEMM computation. That pre-profiling process computes a lot of variables such as frag_per_iter, num_mask_per_thread, and data types, etc. ahead of  C++ compiling so that the compiling can unroll the loop if any of those variables are defined as the num of iterations. And some values are also dependent on the input data, like tile_shape should vary with the input matrix shape for better performance. Considering that I'm only interested in the platform Ampere, how do I pick up the best parameters for my C++ only package. I know I can print those variables pre-computed by python and hardcoding them with C++, yet there is a huge amount of variables, which makes printing and copying unpractical. And some values are data-dependent, how to find out the computation function of those values efficiently?

2. Apart from variables are pre-computed, some methods seem also chosen in the runtime of python code before C++ compiling, e.g. the sparse iterator in my case is ForwardDgradSparseIOIterator, although the comment denotes "This class is deprecated
". Since I didn't dig deeper into your code, I would be interested to know how the iterator classes are chosen?

3. Finally, what suggestions would you offer if one wants to move the GEMM part to C++ only?

Thanks.

**Comment by FindDefinition** [comment]
Firstly the cumm is based on [CUTLASS](https://github.com/NVIDIA/cutlass) which is a C++-only CUDA Gemm library. cumm rewrite almost all cultass code with pccm-based code instead. I don't recommend to develop gemm in C++-only because of two reasons:
1. CUTLASS use too much template meta-programming. there are many template partial specification in CUTLASS. If you aren't familiar with CUTLASS code, It's quite difficult to find correct partial specification of a kernel.
2. It's very hard to debug CUDA kernel.
cumm use python instead of C++ to perform meta-programming, and construct a python gemm simulator to enable better debug.
Here is another gemm (conv) example: [ppl.nn](https://github.com/openppl-public/ppl.nn/tree/master/src/ppl/nn/engines/cuda/impls/src/nn/conv), a macro-based code generation, it's readability is greatly worse than cutlass.

Secondly I need to know the propose of c++-only kernel. Deploy sparse convolution? Research? For deploy, the c++ only spconv package is already in roadmap. For research, I really don't recommend c++-only (CUTLASS-like).

Thirdly Ampere architecture: the most important new feature of Ampere is async copy engine ([cutlass code](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/mma_multistage.h)), which isn't implemented in cumm yet, I plan to release it in 2021.12.31. other features such as new Tensor Core functions are compatible with "Turing" code in cumm.

Answer of your problems:
1. the python code is a code generator framework. they don't select the best parameters, they compute constant parameters for different tile shapes, different GPU features, different Tensor Cores and different type of conv (regular conv or sparse conv). A gemm contains lots of constant that we don't know which is best for a specific input shape, so we provide lots of kernels with different params and find the best one in runtime. the params such as frag_per_iter isn't computed in runtime, they are constant in CUDA code.
A detailed example: we can select sutable tile shape for a input shape, but how about warp tile shape (determine number of warps used in kernel)? How to select [number of stage](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/mma_multistage.h#L303) in Ampere kernels? it's generally impossible to have a best param for all input shape (even one shape), we must provide different implementation and select them in runtime (another way is use nvrtc JIT compiler, but it just delay compile process).
2. the different iterators is used for different algo or different kind of gemm/conv. for sparse convolutions, we need sparse iterators. for Tensor Core kernels, we need smem and warp iterators that support permuted layout. for simt kernels, we can just use simplest iterators.
The reason why deprecated: the "V2Mask" use a better Mask class to handle mask. currently we select it only in "access per vector=0" kernels (kernel that don't use vector load) because V1 version use too much registers.
Generally speaking, if we want to use new features of GPU or use another type of gemm/conv, we may need different iterators and other classes.
3. I need to know your purpose of c++-only to provide advice.

**Comment by gillbam** [comment]
Hi,

Thanks for your reply. This clarifies a lot for your project. My purpose is to search and research different implementations of sparse convolutions in C++ with academic requirements. It looks like that I need to go deeper into the CUTLASS codebase and your code due to the  C++ demand. Again, thanks for your answer and the contribution :)
