### ISSUE TITLE
Bug in conv 1x1

### ISSUE THREAD

**Issue by thangvubk** [traveller59/spconv#450]
It seems a bug in conv 1x1. ``self.weight.view(self.in_channels, self.out_channels)`` should be in ``FILTER_HWIO``

https://github.com/traveller59/spconv/blob/647927ce6b64dc51fbec4eb50c7194f8ca5007e5/spconv/pytorch/conv.py#L232-L240

**Comment by liudakai2** [comment]
I agree with you. It seems the conv-shape is always `(out_channels, *self.kernel_size, in_channels)` due to the constant `ALL_WEIGHT_IS_KRSC = True`, so the commands in `FILTER_HWIO` should be always executed. However, the released code seems contradictory.

![image](https://user-images.githubusercontent.com/50127983/209607160-f28ef271-8414-487a-81a0-0ccec40acb16.png)

**Comment by JiaqingFu** [comment]
![veJGgITsvI](https://github.com/traveller59/spconv/assets/12004134/2410bcf8-380e-4135-8397-3e5edf1ea89f)
like thist can fix bug.
