### ISSUE TITLE
ValueError: ("can't find suitable algorithm for", <ConvOpType.kForward: 0>)

### ISSUE THREAD

**Issue by Miles629** [traveller59/spconv#455]
I used num_channels and the dimension is 18 of features, and I got wrong when I use the SubMConv3d. does spconv can't use the in_channel of 18 dims? I don't understand.
the error I got "ValueError: ("can't find suitable algorithm for", <ConvOpType.kForward: 0>)"

Here is part of the code
```
features  # your features with shape [N, num_channels] the channels I use is 18
x = spconv.SparseConvTensor(features, indices, spatial_shape, batch_size)#until here It successfully run

#got error here, does the channel can't be 18?
spconv.SparseSequential(
        spconv.SubMConv3d(18,
                          18,
                          3,
                          bias=False,
                          indice_key='subm0'),
        nn.BatchNorm1d(out_channels, eps=1e-3, momentum=0.01),
        nn.ReLU(),
        spconv.SubMConv3d(18,
                          18,
                          3,
                          bias=False,
                          indice_key='subm0'),
        nn.BatchNorm1d(out_channels, eps=1e-3, momentum=0.01),
        nn.ReLU(),
    )
```

**Comment by mc171819** [comment]
I got the same error when i try to use FP16，do you solve this?

**Comment by zhangzw12319** [comment]
In summary, for me, make sure that the datatype for point features should be torch.float32.

Debugging Process:
I also met with this issue. At first, I didn't know why. However, when I changed kernel_size in `spconv.SubMConv3d` from 3 to 1, the program reported another exception: `RuntimeError: expected scalar type Double but found Float`. Then, I knew the real reason was that the datatype of point feature tensor should be tensor.float32 compulsorily. And then I added `.to(torch.float32)` at the beginning and changed back the kernel size to 3, and there was no reported error.

I think the error msg is problematic when kernel is not 1(showing "can't find suitable algorithm" at first), which was rather misleading for new beginners.
